name: Dominion
main: me.amori.dominion.DominionPlugin
version: 1.0.0
api-version: '1.20'
commands:
  setclan:
    description: "Update the clan for a specific player"
  clan:
    description: "Open clan selection panel for neutral players"
    aliases: ["clans", "clanpanel"]